kakao:
  admin-key: ${KAKAO_ADMIN_KEY:}
  pay:
    cid: TC0ONETIME
    approval-url: http://localhost:8080/api/payment/kakao/success
    fail-url: http://localhost:8080/api/payment/kakao/fail
    cancel-url: http://localhost:8080/api/payment/kakao/cancel
  alimtalk:
    sender-key: ${KAKAO_SENDER_KEY:}
    template-code: ${KAKAO_ALIMTALK_TEMPLATE_CODE:}
